### ISSUE TITLE
Issue in training

### ISSUE THREAD

**Issue by Krishnapixels** [breadbread1984/LAPGAN-pt#1]
I tried running this code. I am not able to train. This is the error I am receiving---

WARNING:root:Pytorch Functional was renamed to Pytorch Symbolic!
WARNING:root:Please import pytorch_symbolic instead!
Seed set to 1234
Traceback (most recent call last):
  File "/content/LAPGAN-pt/train.py", line 39, in <module>
    main();
  File "/content/LAPGAN-pt/train.py", line 16, in main
    parser = pl.Trainer.add_argparse_args(parser);
AttributeError: type object 'Trainer' has no attribute 'add_argparse_args'

**Comment by szmikler** [comment]
Install older version of `pytorch_lightning`. Maybe 1.9.4.

**Comment by Krishnapixels** [comment]
Thank you. But now it seems to have problem with the data format.
